services:
  frontend:
    build:
      context: ./frontend
      target: prod
    ports:
      - "4200:4200"
    env_file: ./frontend/.env.prod
    depends_on:
      - backend
    networks:
      - frontend-backend
  backend:
    build: 
      context: ./backendntend
      target: prod
    ports:
      - "8080:8080"
    env_file: ./backendntend/.env.prod
    depends_on:
      - db
    networks:
      - backend-db
      - frontend-backend 
  db:
    image: mysql:8
    env_file:
      - ./mysql-db/.env.prod
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - backend-db
    expose:
      - 3306 

volumes:
  db_data:     

networks:
  frontend-backend:
  backend-db: