services:
  frontend:
    build:
      context: ./react-frontend
      target: dev
    ports:
      - "4200:4200"
    env_file: ./react-frontend/.env.dev
    volumes:
      - ./react-frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - frontend-backend
  backend:
    build:
      context: ./spring-backend
    ports:
      - "8080:8080"
    env_file: ./spring-backend/.env.dev
    depends_on:
      - db
    networks:
      - backend-db
      - frontend-backend 
  db:
    image: mysql:8
    env_file:
      - ./mysql-db/.env.dev
    ports:
      - "3306:3306" 
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - backend-db

volumes:
  db_data:     

networks:
  frontend-backend:
  backend-db: