name: Backend CI pipeline

on:
  push:
    branches: 
      - main
    paths-ignore:
      - '**/*.md'
      - '**/*.env'
  pull_request:
    branches: 
      - main
    paths-ignore:
      - '**/*.md'
      - '**/*.env'

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4.7.1
        with:
          java-version: 11
      
      - name: Run tests with Maven
        working-directory: ./spring-backend
        run: ./mvnw test

      
  # build:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4

  #     - name: Set up JDK 11
  #       uses: actions/setup-java@v4.7.1
  #       with:
  #         java-version: 11

  #     - name: Build with Gradle
  #       run: ./gradlew build