name: Backend CI pipeline

on:
  push:
    branches: 
      - main
    paths-ignore:
      - '**/*.md'
      - '**/*.env'
  pull_request:
    branches: 
      - main
    paths-ignore:
      - '**/*.md'
      - '**/*.env'



jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    services:
      db: 
       image: mysql:8
       env:
         MYSQL_ROOT_PASSWORD: 1
         MYSQL_DATABASE: hobbie_backend_db
       ports:
         - 3306:3306
       
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4.7.1
        with:
          java-version: 11
          distribution: liberica
      
      - name: Wait for MySQL to be ready
        run: |
          for i in {1..30}; do
            if mysqladmin ping -h127.0.0.1 -uroot -p1 --silent; then
              echo "MySQL is ready!"
              break
            fi
            echo "Waiting for MySQL..."
            sleep 2
          done

      - name: Run tests with Maven
        working-directory: ./spring-backend
        run: mvn test -Dspring.datasource.url=jdbc:mysql://127.0.0.1:3306/hobbie_backend_db?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=Europe/Paris


      
  # build:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4

  #     - name: Set up JDK 11
  #       uses: actions/setup-java@v4.7.1
  #       with:
  #         java-version: 11

  #     - name: Build with Gradle
  #       run: ./gradlew build